version: "3"
services:

  nginx:
    image: nginx:latest
    ports: 
      - "8080:80"
    volumes:
      - ./client:/usr/share/client
      - ./server:/usr/share/server
      - ./default.conf:/etc/nginx/conf.d/default.conf

